### ISSUE TITLE
Cannot export resource pack - Mcpacks.net returned 403 Forbidden

### ISSUE THREAD

**Issue by yukaling** [unnamed/emojis#10]
I encountered an exception while starting up my server, here is log:

```
[16:22:07] [Server thread/INFO]: [unemojis] Loaded 21 emojis.
[16:22:07] [Server thread/INFO]: [unemojis] Exporting resource-pack...
[16:22:08] [Server thread/WARN]: [unemojis] Resource-pack icon not found (must be at unemojis/icon.png), using a default one
[16:22:09] [Server thread/ERROR]: Error occurred while enabling unemojis v1.3.2-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: Cannot export resource pack
	at team.unnamed.emojis.resourcepack.export.DefaultExportService.export(DefaultExportService.java:41) ~[emojis-plugin-1.3.2-SNAPSHOT-all.jar:?]
	at team.unnamed.emojis.EmojisPlugin.onEnable(EmojisPlugin.java:68) ~[emojis-plugin-1.3.2-SNAPSHOT-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://mc-packs.net/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at team.unnamed.emojis.resourcepack.export.impl.MCPacksHttpExporter.export(MCPacksHttpExporter.java:107) ~[emojis-plugin-1.3.2-SNAPSHOT-all.jar:?]
	at team.unnamed.emojis.resourcepack.export.DefaultExportService.export(DefaultExportService.java:38) ~[emojis-plugin-1.3.2-SNAPSHOT-all.jar:?]
	... 12 more
[16:22:09] [Server thread/INFO]: [unemojis] Disabling unemojis v1.3.2-SNAPSHOT
```

**More Details**
**Minecraft Version:** 1.18.2 Vanilla
**Server Core:** Paper
**Plugin Version:** 1.3.2-SNAPSHOT

I hope it can be resolved thanku! :D

**Comment by yusshu** [comment]
It is possible that your hosting provider is blocking HTTP requests to external servers *(mc-packs.net)*, in that case, we can't do anything to fix it, but you could talk to their support

**Comment by yukaling** [comment]
> It is possible that your hosting provider is blocking HTTP requests to external servers _(mc-packs.net)_, in that case, we can't do anything to fix it, but you could talk to their support

I got the point thanku :D
